from django.conf.urls import url, patterns
from polizas.views import *

urlpatterns = patterns(
    '',
    url(
        r'^solicitar/(?P<pk>\d+)/$',
        SolicitudPolizaView.as_view(),
        name='solicitar'
    ),
    url(
        r'^emitirPoliza/(?P<pk>\d+)/$',
        EmitirPoliza.as_view(),
        name='emitir'
    ),
    url(
        r'^generarPDFPolizas/(?P<pk>\d+)/$',
        GeneracionPDFPolizas.as_view(),
        name='generacion-pdf-polizas'
    ),
    url(
        r'^realizar-pago/$',
        PagoTarjeta.as_view(),
        name='realizar_pago'
    ),
    url(
        r'^confirmacion-pago/$',
        ConfirmacionPago.as_view(),
        name='confirmacion_pago'
    ),
    url(
        r'^generarPDF/(?P<pk>\d+)/$',
        GeneracionPDFPolizas.as_view(),
        name='generacion-pdf-polizas'
    ),
    url(
        r'^confirmar/(?P<pk>\d+)/$',
        ConfirmarSolicitud.as_view(),
        name='confirmar-solicitud'
    ),
    url(
        r'^solicitud/send/(?P<pk>\d+)/$',
        'polizas.views.SendEmailSolicitud',
        name='send-solicitud'
    ),
    url(
        r'^solicitud/emitir/(?P<pk>\d+)/$',
        'polizas.views.changeEmitida',
        name='emitir-poliza'
    ),
)
