# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('cotizar', '0001_initial'),
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraDatosCliente',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('es_juridico', models.BooleanField(default=False)),
                ('juridico_RUC', models.CharField(default=b'', max_length=30, blank=True)),
                ('juridico_razon_social', models.CharField(default=b'', max_length=30, blank=True)),
                ('juridico_pais_procedencia', models.CharField(default=b'', max_length=30, blank=True)),
                ('juridico_fecha_constitucion', models.DateField(default=datetime.date(2016, 10, 27))),
                ('placa', models.CharField(max_length=40, null=True)),
                ('motor', models.CharField(max_length=40)),
                ('chasis', models.CharField(max_length=40)),
                ('color', models.CharField(default=b'', max_length=20)),
                ('num_puestos', models.IntegerField(null=True, blank=True)),
                ('nombre2', models.CharField(max_length=20)),
                ('apellido_mat', models.CharField(max_length=20, blank=True)),
                ('apellido_cas', models.CharField(max_length=20, blank=True)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('pais_nacimiento', models.CharField(max_length=30)),
                ('pais_residencia', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=30)),
                ('distrito', models.CharField(max_length=30)),
                ('corregimiento', models.CharField(max_length=30)),
                ('urbanizacion', models.CharField(max_length=30, blank=True)),
                ('edificio', models.CharField(default=b'', max_length=30, blank=True)),
                ('piso', models.CharField(default=b'', max_length=5, blank=True)),
                ('apto', models.CharField(default=b'', max_length=5, blank=True)),
                ('calle_ave', models.CharField(max_length=30, blank=True)),
                ('no_casa', models.CharField(default=b'', max_length=5, blank=True)),
                ('apartado_postal', models.CharField(max_length=30, blank=True)),
                ('telefono_res', models.CharField(max_length=20, blank=True)),
                ('profesion', models.CharField(max_length=30, null=True)),
                ('ocupacion', models.CharField(max_length=30, null=True)),
                ('empresa', models.CharField(max_length=30, null=True)),
                ('actividad_empresa', models.CharField(max_length=30, null=True)),
                ('direccion_empresa', models.CharField(max_length=100, null=True)),
                ('telefono_empresa', models.CharField(max_length=30, blank=True)),
                ('correo_trabajo', models.EmailField(max_length=254, blank=True)),
                ('ilicito', models.CharField(default=b'No', max_length=30, choices=[(b'Si', b'Si'), (b'No', b'No')])),
                ('politico_expuesto', models.CharField(default=b'No', max_length=30, choices=[(b'Si', b'Si'), (b'No', b'No')])),
                ('cargo_politico', models.CharField(max_length=30, blank=True)),
                ('periodo_politico', models.CharField(max_length=30, blank=True)),
                ('nombre_politico', models.CharField(max_length=30, blank=True)),
                ('relacion_politico', models.CharField(max_length=30, blank=True)),
                ('declaracion_prima', models.CharField(default=b'No', max_length=30, choices=[(b'Si', b'Si'), (b'No', b'No')])),
                ('actividad_principal', models.CharField(max_length=100, blank=True)),
                ('ingreso_principal', models.CharField(default=b'<10,000.00', max_length=30, blank=True, choices=[(b'<10,000.00', b'<10,000.00'), (b'10,000.00-30,000.00', b'10,000.00-30,000.00'), (b'30,000.00-50,000.00', b'30,000.00-50,000.00'), (b'>50,000.00', b'>50,000.00')])),
                ('otra_actividad', models.CharField(max_length=100, blank=True)),
                ('otro_ingreso', models.CharField(default=b'<10,000.00', max_length=30, blank=True, choices=[(b'<10,000.00', b'<10,000.00'), (b'10,000.00-30,000.00', b'10,000.00-30,000.00'), (b'30,000.00-50,000.00', b'30,000.00-50,000.00'), (b'>50,000.00', b'>50,000.00')])),
                ('documento', models.NullBooleanField(default=False)),
                ('conductor', models.ForeignKey(related_name='datos', to='cotizar.ConductorVehiculo', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=40)),
                ('actividad', models.CharField(max_length=40)),
                ('relacion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudPoliza',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('num', models.CharField(max_length=20, null=True)),
                ('asegurado', models.CharField(max_length=100)),
                ('id_asegurado', models.CharField(max_length=20)),
                ('nombre_conductor', models.CharField(max_length=20)),
                ('id_conductor', models.CharField(max_length=20)),
                ('nombre_conductor2', models.CharField(max_length=20, null=True)),
                ('id_conductor2', models.CharField(max_length=20, null=True)),
                ('nombre_conductor3', models.CharField(max_length=20, null=True)),
                ('id_conductor3', models.CharField(max_length=20, null=True)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('tipo_acreedor_leasing', models.IntegerField(default=0, null=True, blank=True)),
                ('firmador', models.CharField(max_length=40)),
                ('observaciones', models.CharField(default=b'', max_length=100)),
                ('responsable', models.CharField(default=b'Contratante', max_length=30, choices=[(b'Contratante', b'Contratante'), (b'Asegurado', b'Asegurado'), (b'Otro', b'Otro')])),
                ('nombre_responsable', models.CharField(max_length=20)),
                ('id_responsable', models.CharField(max_length=20)),
                ('tipo_produccion', models.CharField(default=b'Propia', max_length=30, blank=True, choices=[(b'Propia', b'Propia'), (b'Coaseguro Lider', b'Coaseguro Lider'), (b'Coaseguro No Lider', b'Coaseguro No Lider'), (b'Reaseguro Cedido', b'Reaseguro Cedido')])),
                ('tipo_suscripcion', models.CharField(default=b'Individual', max_length=30, blank=True, choices=[(b'Individual', b'Individual'), (b'Colectiva', b'Colectiva')])),
                ('forma_facturacion', models.CharField(default=b'Por Poliza', max_length=30, blank=True, choices=[(b'Por Poliza', b'Por Poliza'), (b'Por Certificado', b'Por Certificado')])),
                ('renovacion_automatica', models.BooleanField(default=False)),
                ('comision', models.BooleanField(default=False)),
                ('def_comision', models.CharField(max_length=30, blank=True)),
                ('grupo_economico', models.CharField(max_length=50, blank=True)),
                ('aprobaciones', models.CharField(max_length=200, blank=True)),
                ('funcionario', models.CharField(max_length=50, blank=True)),
                ('cargo_funcionario', models.CharField(max_length=20, blank=True)),
                ('area_funcionario', models.CharField(default=b'Comercial', max_length=30, blank=True, choices=[(b'Comercial', b'Comercial'), (b'At. al Cliente', b'At. al Cliente'), (b'Fianzas', b'Fianzas'), (b'Seguros', b'Seguros'), (b'Otro', b'Otro')])),
                ('otra_area', models.CharField(max_length=20, blank=True)),
                ('tipo_tdc', models.CharField(default=b'', max_length=30, null=True, choices=[(b'Visa', b'Visa'), (b'Mastercard', b'Mastercad')])),
                ('num_tdc', models.CharField(max_length=20, null=True)),
                ('banco_tdc', models.CharField(max_length=20, null=True)),
                ('expiracion_tdc', models.CharField(max_length=20, null=True)),
                ('dia_cobro', models.CharField(default=b'Solicitada', max_length=30, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12'), (b'13', b'13'), (b'14', b'14'), (b'15', b'15'), (b'16', b'16'), (b'17', b'17'), (b'18', b'18'), (b'19', b'19'), (b'20', b'20'), (b'21', b'21'), (b'22', b'22'), (b'23', b'23'), (b'24', b'24'), (b'25', b'25'), (b'26', b'26'), (b'27', b'27'), (b'28', b'28'), (b'29', b'29'), (b'30', b'30')])),
                ('cuenta_banco_num', models.CharField(max_length=100, null=True)),
                ('cuenta_banco_nombre', models.CharField(max_length=50, null=True)),
                ('cuenta_tipo', models.CharField(default=b'', max_length=30, null=True, choices=[(b'Ahorro', b'Ahorro'), (b'Corriente', b'Corriente')])),
                ('tipo', models.CharField(default=b'Solicitada', max_length=30, choices=[(b'Solicitada', b'Solicitada'), (b'Emitida', b'Emitida')])),
                ('acreedor_leasing', models.ForeignKey(default=0, blank=True, to='administrador.Acreedores', null=True)),
                ('cotizacion', models.ForeignKey(to='cotizar.Cotizacion', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='extradatoscliente',
            name='ref_bancaria',
            field=models.ForeignKey(related_name='bancaria', to='polizas.Referencia', null=True),
        ),
        migrations.AddField(
            model_name='extradatoscliente',
            name='ref_comercial',
            field=models.ForeignKey(related_name='comercial', to='polizas.Referencia', null=True),
        ),
        migrations.AddField(
            model_name='extradatoscliente',
            name='ref_personal',
            field=models.ForeignKey(related_name='personal', to='polizas.Referencia', null=True),
        ),
        migrations.AddField(
            model_name='extradatoscliente',
            name='tipo',
            field=models.ForeignKey(blank=True, to='administrador.TipoVehiculo', null=True),
        ),
    ]
