# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraDatosCliente',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('placa', models.CharField(max_length=40)),
                ('motor', models.CharField(max_length=40)),
                ('chasis', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('nombre2', models.CharField(max_length=20)),
                ('apellido_mat', models.CharField(max_length=20)),
                ('apellido_cas', models.CharField(max_length=20)),
                ('dv', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('pais_nacimiento', models.CharField(max_length=30)),
                ('pais_residencia', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=30)),
                ('distrito', models.CharField(max_length=30)),
                ('corregimiento', models.CharField(max_length=30)),
                ('urbanizacion', models.CharField(max_length=30)),
                ('edificio', models.CharField(default=b'N/A', max_length=30)),
                ('piso', models.CharField(default=b'N/A', max_length=5)),
                ('apto', models.CharField(default=b'N/A', max_length=5)),
                ('calle_ave', models.CharField(max_length=30)),
                ('no_casa', models.CharField(default=b'N/A', max_length=5)),
                ('apartado_postal', models.CharField(max_length=30)),
                ('telefono_res', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('estafeta', models.CharField(max_length=30)),
                ('profesion', models.CharField(max_length=30)),
                ('ocupacion', models.CharField(max_length=30)),
                ('cargo_empresa', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=30)),
                ('actividad_empresa', models.CharField(max_length=30)),
                ('direccion_empresa', models.CharField(max_length=100)),
                ('telefono_empresa', models.CharField(max_length=30)),
                ('fax_empresa', models.CharField(max_length=30)),
                ('correo_trabajo', models.EmailField(max_length=254)),
                ('ilicito', models.BooleanField(default=False)),
                ('politico_expuesto', models.BooleanField(default=False)),
                ('cargo_politico', models.CharField(max_length=30)),
                ('periodo_politico', models.CharField(max_length=30)),
                ('nombre_politico', models.CharField(max_length=30, blank=True)),
                ('relacion_politico', models.CharField(max_length=30, blank=True)),
                ('declaracion_prima', models.BooleanField(default=False)),
                ('actividad_principal', models.CharField(max_length=100, blank=True)),
                ('ingreso_principal', models.CharField(default=b'<10,000.00', max_length=30, choices=[(b'<10,000.00', b'<10,000.00'), (b'10,000.00-30,000.00', b'10,000.00-30,000.00'), (b'30,000.00-50,000.00', b'30,000.00-50,000.00'), (b'>50,000.00', b'>50,000.00')])),
                ('otra_actividad', models.CharField(max_length=100, blank=True)),
                ('otro_ingreso', models.CharField(default=b'<10,000.00', max_length=30, choices=[(b'<10,000.00', b'<10,000.00'), (b'10,000.00-30,000.00', b'10,000.00-30,000.00'), (b'30,000.00-50,000.00', b'30,000.00-50,000.00'), (b'>50,000.00', b'>50,000.00')])),
                ('documento', models.BooleanField(default=False)),
                ('conductor', models.ForeignKey(to='cotizar.ConductorVehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=40)),
                ('actividad', models.CharField(max_length=40)),
                ('relacion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudPoliza',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre_conductor', models.CharField(max_length=20)),
                ('id_conductor', models.CharField(max_length=20)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('acreedor', models.CharField(max_length=40)),
                ('leasing', models.CharField(max_length=40)),
                ('opcion', models.CharField(max_length=40)),
                ('firmador', models.CharField(max_length=40)),
                ('observaciones', models.CharField(default=b'', max_length=100)),
                ('responsable', models.CharField(default=b'Contratante', max_length=30, choices=[(b'Contratante', b'Contratante'), (b'Asegurado', b'Asegurado'), (b'Otro', b'Otro')])),
                ('nombre_responsable', models.CharField(max_length=20)),
                ('id_responsable', models.CharField(max_length=20)),
                ('tipo_produccion', models.CharField(default=b'Propia', max_length=30, choices=[(b'Propia', b'Propia'), (b'Coaseguro Lider', b'Coaseguro Lider'), (b'Coaseguro No Lider', b'Coaseguro No Lider'), (b'Reaseguro Cedido', b'Reaseguro Cedido')])),
                ('tipo_suscripcion', models.CharField(default=b'Individual', max_length=30, choices=[(b'Individual', b'Individual'), (b'Colectiva', b'Colectiva')])),
                ('forma_facturacion', models.CharField(default=b'Por Poliza', max_length=30, choices=[(b'Por Poliza', b'Por Poliza'), (b'Por Certificado', b'Por Certificado')])),
                ('renovacion_automatica', models.BooleanField(default=False)),
                ('comision', models.BooleanField(default=False)),
                ('def_comision', models.CharField(max_length=30)),
                ('grupo_economico', models.CharField(max_length=50)),
                ('aprobaciones', models.CharField(max_length=200)),
                ('funcionario', models.CharField(max_length=50)),
                ('cargo_funcionario', models.CharField(max_length=20)),
                ('area_funcionario', models.CharField(default=b'Comercial', max_length=30, choices=[(b'Comercial', b'Comercial'), (b'At. al Cliente', b'At. al Cliente'), (b'Fianzas', b'Fianzas'), (b'Seguros', b'Seguros'), (b'Otro', b'Otro')])),
                ('otra_area', models.CharField(max_length=20)),
                ('cotizacion', models.ForeignKey(to='cotizar.Cotizacion', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='extradatoscliente',
            name='ref_bancaria',
            field=models.ForeignKey(related_name='bancaria', to='polizas.Referencia'),
        ),
        migrations.AddField(
            model_name='extradatoscliente',
            name='ref_comercial',
            field=models.ForeignKey(related_name='comercial', to='polizas.Referencia'),
        ),
        migrations.AddField(
            model_name='extradatoscliente',
            name='ref_personal',
            field=models.ForeignKey(related_name='personal', to='polizas.Referencia'),
        ),
    ]
